# Generated by Django 5.1.5 on 2025-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_gameinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
