# Generated by Django 5.1.5 on 2025-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_notification_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='/media/avatars/defaultavatar.png', max_length=255),
        ),
    ]
